<?php /*
 * Profile template for frontend
 * 
 */ 
 ?>
 <div class="page-title">
	<h1><?php echo $this->__('My MLM  profile'); ?></h1>
</div>

	<div class="fieldset magemlm-left">
		<h2 class="legend"><?php echo $this->__('Referral Link') ?></h2>
	    <p><Strong>Some very nice referral link</Strong></p>
	 </div>
	 
<div class="fieldset magemlm-right">
	<h2 class="legend"><?php echo $this->__('Your image') ?></h2>
	<?php $customerMagemlm 	= Mage::getModel('magemlm/customer')->load(Mage::helper('customer')->getCustomer()->getId(), 'customer_id'); ?>
	<?php $image			= Mage::getBaseUrl('media') . DS . 'magemlm' . DS . $customerMagemlm->getMagemlmImage(); ?>
	
	<p align="center">
		<img src="<?php echo $image; ?>" width="95%"/>
	</p>
	<p align="center">
		<?php echo $this->__('Your image is uploaded by MLM central') ?>
	</p>
</div>

	<div class="fieldset magemlm-full" style="clear: both;">
		<h2 class="legend"><?php echo $this->__('Structure Data') ?></h2>
        <table id="my-orders-table" class="data-table">
    <colgroup>
    	<col width="1">
    	<col width="1">
    </colgroup>
    	<thead>
            <tr class="first last">
                <th>Data</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <tr class="first last odd">
                <td>100000001</td>
                <td><span class="nobr">5/1/13</span></td>
            </tr>
        </tbody>
 </table>
</div>



