<script>
    jQuery(document).ready(function() {
        jQuery("#org").jOrgChart({
            chartElement : '#chart',
            dragAndDrop : true
        });
    });
</script>
<?php // create collectio //

    function displayStructure ($refferalId) {
        
        $collection       = Mage::getModel('magemlm/customer')->getCollection()->addFieldToFilter('refferer_id' , array ('eq' => $refferalId));
        $structureHTML    = 'some text';
        
        if ($collection->count() > 0) {
            echo '<ul>' ;
            foreach ($collection as $customer) {
                echo '<li>' ;
                $image           = Mage::getBaseUrl('media') . DS . 'magemlm' . DS  . $customer->getMagemlmImage();
                echo '<img src="'. $image . '" width="60px" /> ';
                displayStructure ($customer->getCustomerId());
                echo '</li>' ;
            }
            echo  '</ul>';
        }
        
    }
   
?>
 <ul id="org" style="display:none;">
    <li>
       <?php echo Mage::app()->getStore()->getName() ; ?>
       <?php displayStructure(0); ?>
    </li>
    
</ul> 


<div id="chart" class="orgChart"></div>

<script>
        jQuery(document).ready(function() {            
            jQuery('#list-html').text(jQuery('#org').html());
        });
</script>